# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ffTestStatistic <- function(S1, S2, method) {
    .Call(`_fasano_franceschini_test_ffTestStatistic`, S1, S2, method)
}

permutationTestPvalue <- function(zLess, zEqual, nPermute) {
    .Call(`_fasano_franceschini_test_permutationTestPvalue`, zLess, zEqual, nPermute)
}

permutationTestPvalueSeeded <- function(zLess, zEqual, nPermute, seed) {
    .Call(`_fasano_franceschini_test_permutationTestPvalueSeeded`, zLess, zEqual, nPermute, seed)
}

permutationTestSeeded <- function(S1, S2, nPermute, verbose, method, seed) {
    .Call(`_fasano_franceschini_test_permutationTestSeeded`, S1, S2, nPermute, verbose, method, seed)
}

permutationTest <- function(S1, S2, nPermute, verbose, method) {
    .Call(`_fasano_franceschini_test_permutationTest`, S1, S2, nPermute, verbose, method)
}

permutationTestParallel <- function(S1, S2, nPermute, method) {
    .Call(`_fasano_franceschini_test_permutationTestParallel`, S1, S2, nPermute, method)
}

permutationTestParallelSeeded <- function(S1, S2, nPermute, method, seed) {
    .Call(`_fasano_franceschini_test_permutationTestParallelSeeded`, S1, S2, nPermute, method, seed)
}

