# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ffTestStatistic <- function(S1, S2, method) {
    .Call(`_fasano_franceschini_test_ffTestStatistic`, S1, S2, method)
}

permutationTestSeeded <- function(S1, S2, nPermute, verbose, method, seed, tol) {
    .Call(`_fasano_franceschini_test_permutationTestSeeded`, S1, S2, nPermute, verbose, method, seed, tol)
}

permutationTest <- function(S1, S2, nPermute, verbose, method, tol) {
    .Call(`_fasano_franceschini_test_permutationTest`, S1, S2, nPermute, verbose, method, tol)
}

permutationTestParallel <- function(S1, S2, nPermute, method, tol) {
    .Call(`_fasano_franceschini_test_permutationTestParallel`, S1, S2, nPermute, method, tol)
}

permutationTestParallelSeeded <- function(S1, S2, nPermute, method, seed, tol) {
    .Call(`_fasano_franceschini_test_permutationTestParallelSeeded`, S1, S2, nPermute, method, seed, tol)
}

