# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ffTestStatistic <- function(S1, S2) {
    .Call(`_fasano_franceschini_test_ffTestStatistic`, S1, S2)
}

permutationTestSeeded <- function(S1, S2, nPermute, verbose, seed) {
    .Call(`_fasano_franceschini_test_permutationTestSeeded`, S1, S2, nPermute, verbose, seed)
}

permutationTest <- function(S1, S2, nPermute, verbose) {
    .Call(`_fasano_franceschini_test_permutationTest`, S1, S2, nPermute, verbose)
}

permutationTestParallel <- function(S1, S2, nPermute) {
    .Call(`_fasano_franceschini_test_permutationTestParallel`, S1, S2, nPermute)
}

